import gymnasium as gym
from gymnasium import spaces
import numpy as np
import pandas as pd
from typing import Tuple

class ApexMetaEnv(gym.Env):
    """
    Gym environment for tuning Ensemble weights and risk dynamically.
    
    Observation space (6 dimensions):
        0: prob_trending (current regime probability)
        1: prob_ranging
        2: atr_ratio (volatility)
        3: recent_accuracy (rolling win rate of ensemble)
        4: ob_bull_dist
        5: ob_bear_dist
        
    Action space (3 dimensions):
        0: raw_weight_trending
        1: raw_weight_ranging
        2: raw_risk_multiplier
        
    Reward:
        PnL generated by the simulated trade at this step.
    """
    
    def __init__(self, data: pd.DataFrame, initial_balance: float = 10000.0, threshold: float = 0.60):
        super().__init__()
        
        # We expect data to have columns:
        # ['prob_trending', 'prob_ranging', 'atr_ratio', 'recent_accuracy', 'ob_bull_dist', 'ob_bear_dist',
        #  'pred_trending', 'pred_ranging', 'forward_return']
        self.data = data.reset_index(drop=True)
        self.initial_balance = initial_balance
        self.threshold = threshold
        
        # Action: [-1, 1] mapped to Softmax weights and [0.5, 2.0] risk
        self.action_space = spaces.Box(
            low=-1.0, high=1.0, shape=(3,), dtype=np.float32
        )
        
        # Observation
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(6,), dtype=np.float32
        )
        
        self.current_step = 0
        self.balance = self.initial_balance
        self.peak_balance = self.initial_balance
        self.win_rate = 0.5
        
    def reset(self, seed=None, options=None) -> Tuple[np.ndarray, dict]:
        super().reset(seed=seed)
        self.current_step = 0
        self.balance = self.initial_balance
        self.peak_balance = self.initial_balance
        self.win_rate = 0.5
        
        return self._get_obs(), {}
        
    def step(self, action: np.ndarray) -> Tuple[np.ndarray, float, bool, bool, dict]:
        row = self.data.iloc[self.current_step]
        
        # 1. Map actions
        w_raw = np.array([action[0], action[1]])
        w_exp = np.exp(w_raw - np.max(w_raw))
        weights = w_exp / np.sum(w_exp)
        
        weight_trending = weights[0]
        weight_ranging = weights[1]
        
        # Map risk from [-1, 1] to [0.5, 2.0]
        risk_multiplier = 0.5 + ((action[2] + 1.0) / 2.0) * 1.5
        
        # 2. Compute final probability using agent's chosen weights
        pred_trending = row['pred_trending']
        pred_ranging = row['pred_ranging']
        
        final_prob = (pred_trending * weight_trending) + (pred_ranging * weight_ranging)
        
        # 3. Simulate execution
        position_dir = 0
        if final_prob > self.threshold:
            position_dir = 1
        elif final_prob < (1.0 - self.threshold):
            position_dir = -1
            
        # 4. Compute Reward (PnL)
        forward_return = row['forward_return']
        pnl_pct = position_dir * forward_return * risk_multiplier
        pnl_usd = self.balance * pnl_pct
        
        self.balance += pnl_usd
        self.peak_balance = max(self.peak_balance, self.balance)
        
        reward = pnl_pct * 100.0  # Reward is percentage return
        
        # Drawdown penalty
        drawdown = (self.peak_balance - self.balance) / self.peak_balance
        if drawdown > 0.10:
            reward -= (drawdown * 10.0) # Heavy penalty for DD > 10%
            
        self.current_step += 1
        done = self.current_step >= len(self.data) - 1
        truncated = self.balance <= self.initial_balance * 0.5
        
        info = {
            "balance": self.balance,
            "weight_trending": weight_trending,
            "weight_ranging": weight_ranging,
            "risk_multiplier": risk_multiplier,
            "final_prob": final_prob,
            "position": position_dir
        }
        
        return self._get_obs(), float(reward), done, truncated, info
        
    def _get_obs(self) -> np.ndarray:
        row = self.data.iloc[self.current_step]
        return np.array([
            row['prob_trending'],
            row['prob_ranging'],
            row['atr_ratio'],
            row['recent_accuracy'],
            row['ob_bull_dist'],
            row['ob_bear_dist']
        ], dtype=np.float32)
